### ISSUE TITLE
RFC: supporting portless services

### ISSUE THREAD

**Issue by alokat** [andres-erbsen/dename#20]
It would be very cool if external services like https://github.com/WhisperSystems/TextSecure/ could be supported in the profile. But at the moment the key for a value is the port number. So what about port less services in general?
One way could be to use some port numbers, that would probably never be supported, like "Symantec NetBackup Database" 13785. :)
Another way could be to use the name of the tool as key. Names like gpg, pgp or openpgp could all mapped
to the same key -> e.g. pgp.

Any comments?

**Comment by ariddell** [comment]
I like this. Along the same lines, it might be useful to put tor public keys (e.g., for HS lookup or for client auth) into dename.

**Comment by alokat** [comment]
Yeah good point! And what about services like Twitter. It uses port 443, but is not my http oder web url.

**Comment by andres-erbsen** [comment]
I have nothing against adding field numbers for services that do not have a unique port. In fact, "ssh-host" has nothing to do with port 21 that is assigned to it in `client/profile.go`. I think it is a good idea to avoid collisions with port numbers of applications which one could think are integrated with dename, but sticking to standard port numbers is not a goal of its own.

The limitation that a profile maps positive int32-s to byte sequence is rather inherent in the current implementation and I would rather leave it that way. After all, the structure and meaning of the contents of the field will need to be specified externally anyway. And they really need to: it is not obvious that the PGP fingerprint is stored as hex but without spaces instead of being stored in binary (and maybe we should change it to binary before it's too late?).

**Comment by alokat** [comment]
Well if dename expects a 40 bit HEX string for gpg, than it could be checked before it will be added to the
profile.

Besides if you use the gpg command, the fingerprint it already in hex, so I don't see any benefit of changing it.

**Comment by alokat** [comment]
Or the documentation can be changed in order to describe a command like this one:

$ dnmgr set bob pgp "96E8 90D2 6E17 3C7A 53A9  A763 30CB E1DE 82D8 42D8"

and the spaces can be removed before the fingerprint gets stored.
