### ISSUE TITLE
Clients should send writes to a leaders only

### ISSUE THREAD

**Issue by andres-erbsen** [andres-erbsen/dename#23]
(leader = server with "IsCore = true" in config file. I should probably just rename that archaism in the conf and code)

A client currently tries all servers in a loop to complete its operation (get or set). However, it is actually known ahead of time that non-leader servers are unable to handle set-s on their own, so the client should limit itself to leaders in that case. This probably requires adding a field to each server in the client config file.

**Comment by alokat** [comment]
After installing the latest version I get this error:

operation failed: not enough valid signatures for consensus (1 out of 2)

If I want to set a field for my own server.

**Comment by andres-erbsen** [comment]
Hopefully works now. Could you please update the client software, apply the config change from the readme, and try again to confirm?

**Comment by alokat** [comment]
Working on it. My net is fucking slow right now .. that's why it's still gonna take a couple of minutes. :)

**Comment by alokat** [comment]
Hmm. It works if I set my dename and dename-transport keys. But if I try to reset my email, I get the same error.

Server cfg:

[backend]
DataDirectory = /var/dename/leveldb
SigningKeyPath = /var/dename/keys/secret_key
Listen = dename.alokat.org:8877
[frontend]
TransportKeyPath = /var/dename/keys/transport-sk
Listen = dename.alokat.org:6263
[server "dename.mit.edu:8877"]
PublicKey = CiCheFqDmJ0Pg+j+lypkmmiHrFmRn50rlDi5X0l4+lJRFA==
IsCore = true
[server "dename.alokat.org:8877"]
PublicKey = CiD6CFKBpG54dG3OMx6PJ58z5rlNFK24Dx2HMpR7urHIVA==



Client cfg:

[freshness]
Threshold = 60s
NumConfirmations = 1

[server "dename.mit.edu:6263"]
PublicKey = CiCheFqDmJ0Pg+j+lypkmmiHrFmRn50rlDi5X0l4+lJRFA==
TransportPublicKey = 4f2i+j65JCE2xNKhxE3RPurAYALx9GRy0Pm9c6J7eDY=
[server "dename.alokat.org:6263"]
publickey = CiD6CFKBpG54dG3OMx6PJ58z5rlNFK24Dx2HMpR7urHIVA==
transportpublickey = IoEJsVcspYNiuymi+JMpfkL1usDy482qE8V4aGvKrkY=
ReadOnly = true

**Comment by alokat** [comment]
Now I get the same error, if I tray to reset my dename and dename-transport keys.

**Comment by andres-erbsen** [comment]
Confirmed, it indeed did error as you described.

This was caused by your client performing a set on dename.mit.edu and then doing a lookup to confirm that the set was indeed applied (because just a doing a write would not give the dename consistency guarantee). If the lookup ran against dename.mit.edu, you got the 1/2 error because dename.mit.edu did not present your server's signature to your client. If the lookup ran against your server, everything passed.

I now added dename.alokat.org to the config of dename.mit.edu, so dename.mit.edu presents both signatures, and this issue does not appear for me anymore. However, having everybody who wants to run a server contact me is not the way I want this to work.

For everything to go smoothly, set requests need to be sent to a leader, and lookups need to be performed against a server that has all the other servers (or at least sufficient quorum) in its config file. Therefore there probably should be a flag similar ReadOnly (but WriteOnly sounds bad).

NotForSets, NotForLookups?  
NoSets, NoLookups?  
NoWrites, NoLookups?

**Comment by alokat** [comment]
Everything works as expected. Thank you for that.
Indeed, adding new servers manually to a kind of Root server is not really what you want to do. 
Looks like there is still work to do, in order to get the network more self organist.

**Comment by alokat** [comment]
I'm not quite familiar with the namecoin approach, but what about the following approach.

1) all servers can receive changes
2) there is flag - initial 0 - that indicates the number of updates of a profile and gets increased on every update.
3) if a server receives a set for a profile (update), it will broadcast this send to very of its known servers
4) every server that gets this broadcast, checks the number of the update flag and if this flag is < this server will update its version of this profile, otherwise it will send back his version of the profile, because it has the latest one.

This causes more traffic between the servers, but the user will not update his profile every 10 seconds -
I guess.

**Comment by andres-erbsen** [comment]
I really do want all this to be as seamless as possible, but "as possible" is a quite strong limitation. Having all write requests go through a leader (or a group of leaders that all agree that exactly they are the leaders) is necessary to prevent forks (which could otherwise be easily caused by sending different servers a different update with the same version number). It would be possible the have servers present signatures given to them from unknown sources, but considering that all signatures are included in every reply to every client, this would open up a trivial denial-of-service attack (just send each server many bogus signatures to make the reply too big to download). Therefore, a human needs to specify which signatures a server presents. A client configuration that specifies which servers are trusted is necessary for obvious reasons, and using it to workaround the server-side limitations seems like a natural thing to do.

**Comment by alokat** [comment]
I see. Thanks for the hint. Maybe I should do more research on this topic ... :)

**Comment by andres-erbsen** [comment]
After pull request #29, the following config should work regardless of how dename.mit.edu is configured. In case of more then two servers, the lookup server would be the one that knows about all other servers. Clients won't be able to mix and match servers abitrarily, but they can choose any subset of verifiers known to a single lookup server of their choice. I am not sure how we could do better than that. For example, downloading signatures from multiple servers in parallel would be flaky when there are concurrent updates -- some servers would give the client a signature for the state before the update and some would give the state after, resulting in another lack-of-quorum error. Does that qualify as an acceptable solution for you?

    [verification]
    verifier = CiCheFqDmJ0Pg+j+lypkmmiHrFmRn50rlDi5X0l4+lJRFA==
    verifier = CiD6CFKBpG54dG3OMx6PJ58z5rlNFK24Dx2HMpR7urHIVA==

    [freshness]
    Threshold = 60s
    NumConfirmations = 2

    [update "dename.mit.edu:6263"]
    TransportPublicKey = 4f2i+j65JCE2xNKhxE3RPurAYALx9GRy0Pm9c6J7eDY=

    [lookup "dename.alokat.org:6263"]
    TransportPublicKey = IoEJsVcspYNiuymi+JMpfkL1usDy482qE8V4aGvKrkY=

**Comment by alokat** [comment]
Looks good to me.
Now everyone can provide a server without any trouble at all -> lookup server.
And if you want to provide an update / verifier server you have to contact the community, in order to avoid some attacks against the network infrastructure.

Thank you for that.

But, this is a major change of the clients behaviour. So we need to make sure everything works as expected if this diff will be merged. And we should describe in the README what each {verfifier/lookup/update} server means, and add an example config for each case.

**Comment by alokat** [comment]
After testing the new config, it looks like you missed this one: :)
NumConfirmations -> SignaturesRequired

**Comment by alokat** [comment]
Looks like, there is a problem with your example config.
This one works as expected:

[verifier "dename.mit.edu"]
PublicKey = CiCheFqDmJ0Pg+j+lypkmmiHrFmRn50rlDi5X0l4+lJRFA==
[verifier "dename.alokat.org"]
PublicKey = CiD6CFKBpG54dG3OMx6PJ58z5rlNFK24Dx2HMpR7urHIVA==

....

And I think this one, is much better than just:
[verification]
verifier = CiCheFqDmJ0Pg+j+lypkmmiHrFmRn50rlDi5X0l4+lJRFA==
verifier = CiD6CFKBpG54dG3OMx6PJ58z5rlNFK24Dx2HMpR7urHIVA==

Because the config is more readable:
[verifier "server"]
[update "server"]
[lookup "server"]

**Comment by ariddell** [comment]
@alokat what commit are you on? I'm hitting an "invalid section" panic on develop and 15607e0109e5f5855d6d9e0d71ed00f2ebbba0d6.

```
[verifier "dename.mit.edu"]
verifier = CiCheFqDmJ0Pg+j+lypkmmiHrFmRn50rlDi5X0l4+lJRFA==
[verifier "dename.alokat.org"]
verifier = CiD6CFKBpG54dG3OMx6PJ58z5rlNFK24Dx2HMpR7urHIVA==
[verifier "dename.isk.cat"]
verifier = CiA7MQ1IutXudkQsXGarcoSGrbP3anQLPLuzxiFS/WmYvA==

[freshness]
Threshold = 60s
NumConfirmations = 2

[update "dename.mit.edu:6263"]
TransportPublicKey = 4f2i+j65JCE2xNKhxE3RPurAYALx9GRy0Pm9c6J7eDY=

[lookup "dename.alokat.org:6263"]
TransportPublicKey = IoEJsVcspYNiuymi+JMpfkL1usDy482qE8V4aGvKrkY=

[lookup "dename.isk.cat:6263"]
TransportPublicKey = wx9x+D5B23ckc04WXMEJ+AwdIR1MgWYOXl0OsMilFl0=
```

**Comment by andres-erbsen** [comment]
@ariddell there is a client config example at the very bottom of <https://github.com/andres-erbsen/dename/blob/client-config-redo/README.md>. I also posted my own current client config at <https://gist.github.com/andres-erbsen/819d94fd046193ce5015>

**Comment by alokat** [comment]
@ariddell I'm on this branch: https://github.com/andres-erbsen/dename/tree/client-config-redo latest commit.

**Comment by ariddell** [comment]
Got it working (problem was stale $GOPATH/pkg).
Here's a gist with my config: https://gist.github.com/ariddell/8df2ab4c4f3de2b80025

I'll just echo @alokat about the advantages of having the details
documented in the README or elsewhere. For example, perhaps it would be
useful to mention that multiple verifiers is OK but only one lookup is
allowed.

The verifier name being arbitrary is ok provided it doesn't look like a
server-ish address (as it does right now in the README, but not in
@andres-erbsen's gist config). Now that I've had to write the config,
however, I think I'd argue for just having a `[verifiers]` section given
that one anticipates that list will contain at minimum 2 verifiers (and
hopefully a few more). If the blockchain approach (vs.  anytrust) is
going to be the guiding analogy, people might even expect to see
something like 5+ verifiers. Or do I have that detail wrong? Also, since
the verifiers aren't servers (there can only be one update and one
lookup server), I find mirroring the lookup and update config setting
potentially confusing.

Thanks for the help getting this working.

**Comment by andres-erbsen** [comment]
I indeed hope that it will be common for a client config to contain multiple verifiers, and the syntax is not meant to discourage that. There can be redundant update servers as long as they all list each other in their respective server configs [like this](https://gist.github.com/andres-erbsen/03d6f2d4eb8b99e66089). Example [client config](https://gist.github.com/andres-erbsen/7f47d5f4baf1dc601847) (the threshold being 2 instead of 3 is to tolerate the flakiness that probably comes from "isk" and "alokat" not having each other listed). Multiple update servers is supported by the software (and covered by automated tests, so hopefully ok), but there won't be more than one any time soon because when any update server is down, no updates can be applied.

The other reason for using the same syntax for verifiers as for update/lookup servers is that if there ever is a need for a verifier entry to have some other property than the public key (clock skew tolerance?), we would need to switch to the longer format anyway.

I will add detailed documentation as soon as the client config format is decided for now. It currently looks good to me; I am looking forward to your feedback.

**Comment by andres-erbsen** [comment]
Merged: 52027bba2440f4ead26ae17ff64837868289ed0e

**Comment by ariddell** [comment]
Just a note to say I'm trying to find some time to update the isk config. I also have a Dockerfile for the server that's working rather well that I need to tidy up slightly.

**Comment by ariddell** [comment]
Added alokat to isk, seems to be working.

Preliminary Dockerfile here: https://github.com/ariddell/dename-verifier-container
