### ISSUE TITLE
cannot get profile information or set profile information

### ISSUE THREAD

**Issue by sebastianrakel** [andres-erbsen/dename#36]
i cannot execute any command

```
sebastian at snotra ~ % dnmgr set sebastianrakel ssh "$(cat ~/.ssh/id_*.pub)"
operation failed: not enough fresh signatures (0 out of 2):
sebastian at snotra ~ % dnmlookup fritjof gpg             
lookup failed: not enough fresh signatures (0 out of 2): 
```

my config and directory structure

```
sebastian at snotra ~ % tree .config/dename
.config/dename
├── authorities.cfg
└── sebastianrakel
    ├── profile
    └── sk
1 directory, 3 files
sebastian at snotra ~ % cat .config/dename/authorities.cfg
[verifier "dename.mit.edu"]
PublicKey = CiCheFqDmJ0Pg+j+lypkmmiHrFmRn50rlDi5X0l4+lJRFA==
 
[verifier "dename.alokat.org"]
PublicKey = CiD6CFKBpG54dG3OMx6PJ58z5rlNFK24Dx2HMpR7urHIVA==
 
#[consensus]
#SignaturesRequired = 2
#[freshness]
#SignaturesRequired = 2
 
[update "dename.mit.edu:6263"]
TransportPublicKey = 4f2i+j65JCE2xNKhxE3RPurAYALx9GRy0Pm9c6J7eDY=
 
[lookup "dename.alokat.org:6263"]
TransportPublicKey = IoEJsVcspYNiuymi+JMpfkL1usDy482qE8V4aGvKrkY=
```

**Comment by andres-erbsen** [comment]
The posted config works for me, and I am not sure where the problem might be. To troubleshoot this, I would

- Make sure that `dnmlookup` and `dnmgr` are up to date (but the error message format is already quite recent)
- Run `go test` in the `server` directory (in case there is something particular to your machine setup that makes things go wrong, it might show up here).
- Try the same without any config
- `fmt.Println(signedHashOfStateMsgs)` at https://github.com/andres-erbsen/dename/blob/master/client/client.go#L306 (in case the server really does not return any signatures to you). To use the modified code, cd to `dnmlookup`, do `go build` and use `./dnmlookup` instead of `dnmlookup`.
- `fmt.Println("failed to validate", msg)` at https://github.com/andres-erbsen/dename/blob/master/client/client.go#L293 (in case the server sent you a bad signature)

**Comment by sebastianrakel** [comment]
ok, this is awkward. i try the same commands again and changed nothing and now it's working. i only waited a day.
